---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-info
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: k8s-info
  namespace: k8s-info
spec:
  interval: 5m0s
  url: oci://ghcr.io/cotyhamilton/k8s-info/charts/k8s-info
  ref:
    tag: 0.1.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-info
  namespace: k8s-info
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: k8s-info
    namespace: k8s-info
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: k8s-info
  namespace: k8s-info
spec:
  parentRefs:
    - name: gateway
  hostnames:
    - "k8s-info.cotyhamilton.com"
  rules:
    - backendRefs:
        - name: k8s-info
          port: 8000
