#cloud-config

# package_update: true
# package_upgrade: true
# package_reboot_if_required: true

runcmd:
  - |
    echo "installing k3s"
    curl -sfL https://get.k3s.io | K3S_TOKEN=${K3S_TOKEN} sh -s - server \
      --tls-san=${K3S_DOMAIN}
