---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-api
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: gateway-api
spec:
  interval: 5m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    tag: v1.2.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: gateway-api
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: gateway-api
  path: "./config/crd/standard"
  prune: true
  timeout: 1m
