---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: traefik
      version: "34.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 5m
  releaseName: traefik
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-certificate-name: cotyhamilton.com
        service.beta.kubernetes.io/do-loadbalancer-http-ports: "80"
        service.beta.kubernetes.io/do-loadbalancer-protocol: http
        service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    ingressRoute:
      dashboard:
        enabled: true
        entrypoints:
          - web
    providers:
      kubernetesGateway:
        enabled: true
    gateway:
      enabled: false
    logs:
      access:
        enabled: true
    ports:
      websecure:
        targetPort: web
